.gitignore, README.md, eessi/reframe/eessi_checks/applications/gromacs_check.py, eessi/reframe/eessi_utils/hooks.py, eessi/reframe/eessi_utils/utils.py
fixes https://github.com/EESSI/test-suite/issues/18
=> move logic that is not specific to gromacs into hooks functions

eessi/reframe/eessi_checks/applications/gromacs_check.py
The `hEGFRDimer` input features a 465K atom system, while the `Crambin` input uses a 20K atom system, so the latter is way better suited to use as CI test, cfr. https://www.hecbiosim.ac.uk/access-hpc/benchmarks
See also https://github.com/EESSI/test-suite/pull/44
=> use smallest input (Crambin) as CI test for GROMACS

.github/workflows/pip_install.yml
fixes #5
Example run: https://github.com/boegel/EESSI-test-suite/actions/runs/5136899209/jobs/9244247829
=> add GitHub Actions workflow to test installation with pip

config/surf_snellius.py
Don't use EESSI_INIT env var, its something I set personally. Add --export=None, even if this is the default on our system, it is a good practice to ensure this
=> use --export=None + don't use custom `$EESSI_INIT` in Snellius config file

scripts/run_reframe.sh, scripts/run_reframe_wrapper.sh
Add scripts that I use to set up a cronjob on Vega. Can easily be used for other systems as well.
=> Vega regular runs

scripts/run_reframe.sh
Don't start ssh agent every time, it keeps on running. Just put github.com in your .ssh/config. Added instructions to do that.
=> Remove starting Github agent from run_reframe script

config/surf_snellius.py
Also: I've put comments on what to (temporarily) change for autodetection to complete succesfully
=> Enable autodetection of CPU topology for Snellius ReFrame config

.github/workflows/test.yml, README.md, config/github_actions.py, config/settings_example.py, config/surf_snellius.py, config/vsc_hortense.py, eessi/testsuite/constants.py, eessi/testsuite/hooks.py, eessi/testsuite/utils.py
fixes #34 
fixes #40 
this PR changes `filter_valid_systems_by_device_type` in `hooks.py` to explicitly require an NVIDIA GPU
from
```python
if is_cuda_module and required_device_type == DEVICES['GPU']:
valid_systems = f'+{FEATURES["GPU"]}'
```
to
```python
if is_cuda_module and required_device_type == DEVICES['GPU']:
valid_systems = f'+{FEATURES["GPU"]} %gpu_vendor={GPU_VENDORS["NVIDIA"]}'
```
=> filter valid_systems on gpu_vendor extras

scripts/run_reframe.sh
Small improvement so we have a bit more info. Also, it was to see if the addition of `--performance-report` also makes sure that performance numbers end up in `reframe_runs/logs/vega/cpu/GROMACS_EESSI_5535abba.log` (it doesn't, so for that, we'll have to look further).
=> Print more info, and add performance report to the stdout

eessi/testsuite/utils.py
Expand functionality of find_modules so that it can be passed a regular expression. It can also ommit the version (i.e. anything after the last slash) from the match, if required.
If you want to define a ReFrame test to play around with the new `find_modules` functionality:
```
import reframe as rfm
import reframe.utility.sanity as sn
from eessi.testsuite import hooks, utils
from eessi.testsuite.constants import *
@rfm.simple_test
class find_modules(rfm.RunOnlyRegressionTest):
valid_prog_environs = ['default']
valid_systems = ['*']
module_name = parameter(utils.find_modules('^gompi\/', name_only = False))
executable = 'hostname'
time_limit = '5m'
tags = {TAGS['CI']}
```
Then run with e.g. 
```
reframe -C test-suite/config/izum_vega.py -c test-suite/eessi/testsuite/tests/find_modules.py -R …
```
=> Improve find_modules with regex functionality

README.md, config/aws_citc.py, config/github_actions.py, config/izum_vega.py, config/settings_example.py, config/surf_snellius.py, config/vsc_hortense.py, eessi/testsuite/common_config.py, scripts/run_reframe.sh
changes in this PR:
- use common config section for logging
- fix mympirun launcher for hortense
- ~use reframe options `--prefix` and `--save-log-files` to make sure **all** output goes into the prefix~
- support overriding the prefix for file logs with `RFM_PREFIX`
fixes https://github.com/EESSI/test-suite/issues/64
fixes https://github.com/EESSI/test-suite/issues/61
=> use common config section for logging

config/aws_citc.py, config/izum_vega.py, config/settings_example.py, config/surf_snellius.py
... And renamed thin to rome, as the thin partition will be deprecated.
Also, moved and removed some comments related CPU autodetection, since support has improved in ReFrame 4.3.3
=> Added new genoa partition

config/settings_example.py
For now these instructions are still in a HackMD... so this PR might still change a little bit.
At the very least, this alligns with:
- our recommendation to use CPU autodetect
- our recommendation to not export submission environment
- loading of the EESSI software stack inside the test jobs
=> Allign settings_example.py with instructions from docs

RELEASE_NOTES, pyproject.toml, setup.cfg
marked as WIP since #90 ideally gets merged first
Release notes are a carbon copy of what's in https://eessi.io/docs/test-suite/release-notes
=> bump version to 0.1.0, add RELEASE_NOTES

setup.cfg
This was necessary to publish v0.1.0 to PyPI: https://pypi.org/project/eessi-testsuite/0.1.0
=> add content type of long description + license to setup.cfg

eessi/testsuite/constants.py, eessi/testsuite/hooks.py, eessi/testsuite/tests/apps/gromacs.py, eessi/testsuite/tests/apps/tensorflow/tensorflow.py
- add hook ` _assign_num_tasks_per_node` which can be used in the OSU benchmark
- rename hook `assign_one_task_per_compute_unit` to `assign_tasks_per_compute_unit`, to reflect that more than 1 task can be requested per compute unit (currently only implemented for ` _assign_num_tasks_per_node`)
=> add hook to assign tasks per node

.github/workflows/test.yml
will fix:
```
Error: Bad request - cvmfs-contrib/github-action-cvmfs@d4641d0d591c9a5c3be23835ced2fb648b44c04b is not allowed to be used in EESSI/test-suite
```
see also https://github.com/EESSI/github-action-eessi/pull/22
=> use latest version of `eessi/github-action-eessi`

.github/workflows/pip_install.yml, .github/workflows/scorecards.yml, .github/workflows/test.yml
fix for
```
error: externally-managed-environment
× This environment is externally managed
╰─> 
The system-wide Python installation in Gentoo should be maintained
using the system package manager (e.g. emerge).
If the package in question is not packaged for Gentoo, please
consider installing it inside a virtual environment, e.g.:
python -m venv /path/to/venv
. /path/to/venv/bin/activate
pip install mypackage
To exit the virtual environment, run:
deactivate
The virtual environment is not deleted, and can be re-entered by
re-sourcing the activate file.
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 …
```
=> use venv rather than 'pip install --user' in CI workflow to test test suite

.github/workflows/test.yml
Fix for indirect switch to `software.eessi.io` in #102
We have to keep using the EESSI pilot repo for now, since `software.eessi.io` does not provide GROMACS yet (cfr. https://github.com/EESSI/software-layer/pull/401)
=> use EESSI pilot repo for testing test suite (for now)

eessi/testsuite/tests/apps/gromacs.py, eessi/testsuite/tests/apps/osu.py, eessi/testsuite/tests/apps/tensorflow/tensorflow.py
As far as I can tell, there's no way to tweak the test name, it's always determined by the Python class name (see https://reframe-hpc.readthedocs.io/en/stable/manpage.html#test-naming-scheme)
Before these changes (with EESSI pilot 2021.12 as available modules):
```
$ reframe --list --system hortense:cpu_rome_256gb --tag CI --tag 2_cores
...
[List of matched checks]
- GROMACS_EESSI %benchmark_info=HECBioSim/Crambin %nb_impl=cpu %scale=2_cores %module_name=GROMACS/2020.4-foss-2020a-Python-3.8.2 /1d77cf1a
- GROMACS_EESSI %benchmark_info=HECBioSim/Crambin %nb_impl=cpu %scale=2_cores %module_name=GROMACS/2020.1-foss-2020a-Python-3.8.2 /9857398f
- osu_coll %benchmark_info=mpi.collective.osu_allreduce %scale=2_cores %module_name=OSU-Micro-Benchmarks/5.7.1-gompi-2021a %device_type=cpu /82cca1df
- …
```
=> unify test names: `EESSI_` + software name (with '`-`' replaced by '`_`') + optional label for type of test

config/software_layer_bot.py
Need this for the functionality being implemented in https://github.com/EESSI/software-layer/pull/467
=> Added config for automatically running test suite after software layer build jobs by the bot

config/aws_mc.py, config/github_actions.py, config/it4i_karolina.py, config/izum_vega.py, config/settings_example.py, config/surf_snellius.py, config/vsc_hortense.py, eessi/testsuite/constants.py, eessi/testsuite/hooks.py, eessi/testsuite/tests/apps/gromacs.py, eessi/testsuite/tests/apps/osu.py, eessi/testsuite/tests/apps/tensorflow/tensorflow.py
This avoids issues on Snellius GPU, where partially allocating multiple nodes is not allowed by the Slurm configuration.
=> Add new hook to filter invalid scales based on features set in the config file

eessi/testsuite/hooks.py, eessi/testsuite/tests/apps/osu.py
1. The default `device_buffers` is set in `run_after_init`.
2. Changed the valid systems settings in `hooks.py` addressing https://github.com/EESSI/test-suite/issues/101 .
=> do not run cuda modules on non-gpu partitions

eessi/testsuite/tests/apps/osu.py
The collective tests do not get listed unless the default valid systems is set to this:
`valid_systems = ['*']`
The reason is: they all get set to `[INVALID]` state.
=> Collective OSU tests not getting listed due to initialisation of default `valid_systems`.

eessi/testsuite/constants.py, eessi/testsuite/hooks.py, eessi/testsuite/tests/apps/osu.py, setup.cfg
fixes #115 
changes:
- add feature `always_request_gpus` for partitions that require it, and check for it in hook `check_always_request_gpus`, called at end of hook `assign_tasks_per_compute_unit` to ensure it is run *after* task assignment
- small hook updates to allow simplifying the OSU test (done for the pt2pt test, not yet for collective test)
- filter scale `2_cores` for device_type `gpu` (in addition to skipping single-node tests with only 1 GPU present in the node), as this scale has only 1 GPU (pt2pt test)
- add flake8 configuration to setup.cfg
i did not add the new feature to the config files in the repo as there are currently no partitions that have both feature `cpu` and `gpu`, although it does not hurt to add it to all GPU partitions that do not have feature `cpu` (it should …
=> support always requesting GPUs on partitions that require it

.github/workflows/linting.yml, config/aws_mc.py, config/github_actions.py, config/it4i_karolina.py, config/izum_vega.py, config/settings_example.py, config/surf_snellius.py, config/vsc_hortense.py, eessi/testsuite/common_config.py, eessi/testsuite/hooks.py, eessi/testsuite/tests/apps/gromacs.py, eessi/testsuite/tests/apps/osu.py, eessi/testsuite/tests/apps/tensorflow/src/mnist_setup.py, eessi/testsuite/tests/apps/tensorflow/src/tf_test.py, eessi/testsuite/tests/apps/tensorflow/tensorflow.py, eessi/testsuite/utils.py
fixes https://github.com/EESSI/test-suite/issues/119
- add python-linting workflow
- no functional changes, only formatting fixes
=> code formatting

config/aws_mc.py, config/it4i_karolina.py, config/izum_vega.py, config/settings_example.py, config/surf_snellius.py, config/vsc_hortense.py, eessi/testsuite/common_config.py
It would be nice if we can add a timestamp instead of the session id, so we can more easily relate these to their corresponding performance logs. But since it is a common config item, we can easily update that later.
=> Add common config item to redirect the report file to the same directory as e.g. the perflog

CI/aws_mc/ci_config.sh
So remove the exception for the CI on `aws_mc` to use the pilot repo.
=> software.eessi.io is now also present on the AWS MC cluster

.github/workflows/scorecards.yml
Prevent running of scorecards CI workflow on forks
=> Prevent running scorecards CI on forks

eessi/testsuite/hooks.py
Currently, the mapping was set by node. That is NOT the same thing as compact process binding, since for e.g. 2 nodes 4 tasks it will lead to task 0 on node 0, task 1 on node 1, task 2 on node 0, task 3 on node 1. Compact would have been task 0 and 1 on node 0, and task 2 and 3 on node 1. Thus, this was a bug.
Mapping by slot (combined with specifying PE=n) IS correct. The PE=n will set cpus-per-rank to n (see https://www.open-mpi.org/doc/current/man1/mpirun.1.php), while mapping by slot will mean that each rank is mapped to a consecutive slot. The only scenario in which mapping by slot will result in non-compact mapping is if oversubscription is enabled - then the oversubscribed ranks will be assigned round robin to the slots. This shouldn't be an issue for the test suite, we don't do …
=> Fix compact process binding for OpenMPI mpirun

config/github_actions.py, eessi/testsuite/hooks.py, eessi/testsuite/tests/apps/gromacs.py, eessi/testsuite/utils.py
Without process binding, `mpirun` was binding processes to NUMA domains. I'm not sure why, but occasionally I saw some cores  on Snellius being empty, while others seemed to run 2 processes. These runs would run about 10x slower than normal. This must be some weird behaviour from the OS thread scheduler. With process binding, performance is more consistent: while I still see some variation, I don't see the extremely slow runs anymore. Also, it seems performance also went up a bit (few %) on average, though it is a bit hard to be sure with the natural variation between runs.
Depends on:
=> Use compact process binding for gromacs

eessi/testsuite/constants.py, eessi/testsuite/tests/apps/osu.py
fixes https://github.com/EESSI/test-suite/issues/136
adding a warning for the removed scales is not advisable here, as then you still get non-unique tags
however, from the reframe output it's pretty clear there's something wrong with the user provided tags:
>Loaded 624 test(s)
Generated 36 test case(s)
Filtering test cases(s) by name: 36 remaining
Filtering test cases(s) by tags: 0 remaining
Filtering test cases(s) by other attributes: 0 remaining
Final number of test cases: 0
=> Rename scale tags 1_cpn_2_nodes and 1_cpn_4_nodes

eessi/testsuite/tests/apps/osu.py
Tests on e.g. the AWS Magic Castle cluster have been pretty slow, especially the collectives that send a ton of data around. A thousand iterations is definitely overkill, we don't generally need that kind of precision to see when something is wrong. 
An example run with `--reruns=5` and only the bandwidth test for one of the modules produced:
```
[----------] start processing checks
[ RUN      ] EESSI_OSU_Micro_Benchmarks_pt2pt %benchmark_info=mpi.pt2pt.osu_bw %scale=2_nodes %module_name=OSU-Micro-Benchmarks/7.2-gompi-2023b %device_type=cpu /f749ec9f @snellius:genoa+default
[       OK ] (1/1) EESSI_OSU_Micro_Benchmarks_pt2pt %benchmark_info=mpi.pt2pt.osu_bw %scale=2_nodes %module_name=OSU-Micro-Benchmarks/7.2-gompi-2023b %device_type=cpu /f749ec9f @snellius:genoa+default
P: bandwidth: …
```
=> Reduce the iteration count to make the OSU tests run faster, especially on slower interconnects

config/github_actions.py, config/it4i_karolina.py, config/izum_vega.py, config/surf_snellius.py, config/vsc_hortense.py, eessi/testsuite/hooks.py, eessi/testsuite/tests/apps/QuantumESPRESSO.py, eessi/testsuite/tests/apps/espresso/espresso.py
fixes https://github.com/EESSI/test-suite/issues/150
- use MiB for `mem_per_node` in config files
- use MiB for `app_mem_req` argument of hook `req_memory_per_node`
=> use MiB units for memory per node

config/aws_citc.py, config/aws_mc.py, config/it4i_karolina.py, config/izum_vega.py, config/macc_deucalion.py, config/surf_snellius.py, config/vsc_hortense.py, eessi/testsuite/common_config.py
this change allows using either the local modules or EESSI using a single config file.
if `EESSI_CVMFS_REPO` envvar is defined, use EESSI, else use local modules (or from other sources).
EDIT: all config files are now updated
=> make EESSI optional in common_eessi_init

tutorial/mpi4py/mpi4py_portable.py
Change conform https://github.com/EESSI/docs/pull/262/commits/2c19e27cb6ee315b82ffd00e147eab7a110dcd3a
=> Final change to keep things aligned with the EESSI docs

.github/workflows/test.yml
ReFrame 4.6.2 got deployed in EESSI, and is now picked up by the CI. The module is different in that the `external` folder within the ReFrame installation prefix is no longer on the `PYTHONPATH`. As a result, `python -c "import reframe"` doesn't work anymore - and note that this is by design. One should never import ReFrame directly, but only _in a ReFrame test_ that is run by the `reframe` command. The `reframe` command then adds the `external` folder to the `sys.path`. The advantage of this setup is that _only_ ReFrame picks up on those python deps in `external` folder, it doesn't polute the `PYTHONPATH`.
This PR removes the line that does `python -c 'import eessi.testsuite.utils'`, since that is _not_ supposed to work: it indirectly imports `reframe`, which is not supposed to work, as …
=> Fix CI for new ReFrame 4.6.2

config/surf_snellius.py
Previous PR was wrong: it should be a regex, so `.*`, instead of `*`. The latter causes an error ("nothing to repeat").
Fixed with this PR.
=> Fix hostnames in config

config/aws_mc.py, config/azure_mc.py
This PR limits the number of jobs to 1 per partition for the AWS and Azure clusters. This doesn't prevent the issue of crossing the vCPU threshold, but should at least alleviate it.
=> Limit azure aws jobs 1 per partition

eessi/testsuite/eessi_mixin.py, eessi/testsuite/tests/apps/cp2k/cp2k.py
additional improvements to the mixin class:
- add hook `set_tag_ci()` to the mixin class, which is used if both `bench_name_ci` and `bench_name` are set. we could also make this a mandatory attribute, to be discussed.
- make `measure_memory_usage` a reframe variable that can be set on the cmd line with `reframe -S measure_memory_usage=True`
cp2k.py file reduced from 114 lines to 76 \o/
=> use mixin class for cp2k

eessi/testsuite/eessi_mixin.py
Solves https://github.com/EESSI/test-suite/issues/196
Note that the nodenames on which the test is run are already logged by the ReFrame framework, so we don't need to do that.
Discussed on the ReFrame slack channel. The challenge is that we want the variables from the batch nodes, so it has to be printed with `postrun_cmds`. But then, we need to get it from the output, and into a ReFrame `variable` so that it is logged. Those need to be initialized in the class body. Then can be updated with the output of the extracted information. We use sanity functions to extract from the output, catching the SanityError that is produced if there is no match (as we don't want the test to _fail_ because of this). Note that SanityError's are actually expected for runs on local software stack, since then …
=> Collect addional info in mixin

CI/hortense_local_ss/ci_config.sh, config/vsc_hortense.py
I thought that `shed_access_in_submit` would only work with ReFrame 4.7 and older but when testing the CI it also seems to work with 4.6.2. Let me know if this is not the case.
=> Run local stack of Hortense using `shed_access_in_submit`

eessi/testsuite/tests/apps/PyTorch/PyTorch_torchvision.py
still needs testing the required memory per node
EDIT: 1GB per core seems to be enough, ready for review
=> use mixin class for pytorch

eessi/testsuite/eessi_mixin.py, eessi/testsuite/hooks.py, eessi/testsuite/tests/apps/QuantumESPRESSO.py
notes:
- this change may affect performance as process binding is now on by default
~~- the mixin class no longer raises an error if `bench_name` is not defined as it's not really needed, and it helps making the QE test a bit simpler.~~
=>  use mixin class for QuantumESPRESSO

eessi/testsuite/eessi_mixin.py, eessi/testsuite/hooks.py
this is useful in 2 use cases:
- when testing a PR, to make sure the memory requirements are ok
- when comparing performance between partitions with different amounts of memory available
=> add support for setting the exact required memory

CI/run_reframe.sh
mktemp failed if the CI tempdir env var wasn't defined:
```
$ mktemp --directory --tmpdir=${EESSI_CI_TEMPROOT:-HOME}                                                                           mktemp: failed to create directory via template ‘HOME/tmp.XXXXXXXXXX’: No such file or directory
```
because it would try to substitue HOME (as a string), thus trying to create the directory HOME/tmp.XXXXXXXXXX. We _wanted_ the /ceph/hpc/home/eucasparvl environment variable here
=> Bugfix for failing mktemp in CI

eessi/testsuite/eessi_mixin.py, eessi/testsuite/hooks.py, eessi/testsuite/tests/apps/osu.py
EESSI_Mixin class:
- change measure_mem_usage() to `@run_before('setup', always_last=True)` to avoid `perf_variables` being overwritten by the hpctestlib
- set default `num_tasks_per_compute_unit`
OSU test:
- use mixin class
- create base class to minimize code duplication
- reduce required memory per node to 1GB per task
- add partial node scales for the `pt2pt` GPU test and skip the ones that don't have exactly 2 GPUs
fixes https://github.com/EESSI/test-suite/issues/145
=> use mixin class for osu

eessi/testsuite/hooks.py
fixes failure for tests that don't (yet) use the eessi mixin class
`object has no attribute 'always_request_gpus'`
=> fix always_request_gpus attribute

eessi/testsuite/hooks.py
similar fix as https://github.com/EESSI/test-suite/pull/229
>AttributeError: 'EESSI_ESPRESSO_P3M_IONIC_CRYSTALS' object has no attribute 'exact_memory'
=> fix exact_memory attribute

eessi/testsuite/eessi_mixin.py, eessi/testsuite/hooks.py, eessi/testsuite/tests/apps/espresso/espresso.py, eessi/testsuite/tests/apps/gromacs.py, eessi/testsuite/tests/apps/lammps/lammps.py, eessi/testsuite/tests/apps/tensorflow/tensorflow.py
this PR adds a new `variable` `user_executable_opts` to the `EESSI_Mixin` class, which users can specify on the cmd line. advantages:
- gives users full control of the executable options: it will *completely* override the ones set in the test
- simplifies the tests: no more annoying `check_custom_executable_opts(self, num_default=num_default)` and `has_custom_executable_opts`
- consistency: some tests were using `check_custom_executable_opts` and `has_custom_executable_opts`, others were not.
=> simplify executable_opts with new variable user_executable_opts

config/aws_citc.py, config/aws_mc.py, config/azure_mc.py, config/github_actions.py, config/it4i_karolina.py, config/izum_vega.py, config/macc_deucalion.py, config/settings_example.py, config/surf_snellius.py, config/vsc_hortense.py, eessi/testsuite/constants.py, eessi/testsuite/eessi_mixin.py, eessi/testsuite/hooks.py, eessi/testsuite/tests/apps/MetalWalls.py, eessi/testsuite/tests/apps/PyTorch/PyTorch_torchvision.py, eessi/testsuite/tests/apps/QuantumESPRESSO.py, eessi/testsuite/tests/apps/cp2k/cp2k.py, eessi/testsuite/tests/apps/espresso/espresso.py, eessi/testsuite/tests/apps/gromacs.py, eessi/testsuite/tests/apps/lammps/lammps.py, eessi/testsuite/tests/apps/osu.py, eessi/testsuite/tests/apps/tensorflow/tensorflow.py, eessi/testsuite/utils.py, tutorial/mpi4py/mpi4py_portable_legacy.py, tutorial/mpi4py/mpi4py_portable_mixin.py
fixes https://github.com/EESSI/test-suite/issues/257
also:
- add constant for `extras` key `'mem_per_node'`
- group `extras` constants into `EXTRAS` namedtuple: `EXTRAS.GPU_VENDOR`, `EXTRAS.MEM_PER_NODE`
- change `EESSI_mixin_validate_item_in_dict` method to `EESSI_mixin_validate_item_in_list` to make it simpler and more flexible
=> use namedtuples for constants

config/vsc_hortense.py
use mpirun as launcher
- removed custom launcher mympirun
- set/unset environment variables to make sure mpirun works properly
Required updates after maintenance of hortense
- update memory (more memory is now taken by the OS) 
- A new partition was added for the first part of hortense that is moved to RHEL9
=> Update Hortense config: use `mpirun` launcher + take into changes during maintenance

eessi/testsuite/eessi_mixin.py
Noticed that `module --location show PyTorch/2.1.2-foss-2023a` was returning nothing in stdout. Which ment that the full modulepath was missing from the report-file
```
"full_modulepath": "['']",
```
This is because the module command prints to stderr when `LMOD_REDIRECT=no` which is the case for EESSI. This small fix makes sure that `full_modulepath` will be set either way.
=> Fix output of full_modulepath
