eessi/reframe/config/settings_example.py, eessi/reframe/eessi-checks/applications/gromacs_check.py, eessi/reframe/eessi_utils/hooks.py, eessi/reframe/eessi_utils/utils.py
First test, solves https://github.com/EESSI/test-suite/issues/1
=> Gromacs EESSI on top of CSCS GROMACS library test

eessi/reframe/eessi_checks/applications/gromacs_check.py
fixes https://github.com/EESSI/test-suite/issues/41
=> add more comments, docs to the gromacs test

.github/workflows/test.yml, eessi/reframe/config/github_actions.py
fixes #6
draft because running tests in GitHub Actions doesn't work yet as intended
=> add GitHub Actions workflow to run EESSI test suite in dry run mode

README.md
Added some additional instructions on how to use the git-machinery if you want to e.g. test someone else's feature branch.
=> Expand developer instructions

config/surf_snellius.py
This can serve as yet another example, and is convenient for those of us at SURF who want to run the EESSI test suite.
=> Added config file for Snellius, the SURF supercomputer

eessi/testsuite/hooks.py, eessi/testsuite/tests/apps/gromacs.py, eessi/testsuite/utils.py
fixes https://github.com/EESSI/test-suite/issues/35
=> add debug log statements

config/vsc_hortense.py
Add the prepare commands for EESSI to the config file of vsc_hortense.py
=> initialize EESSI environment via prepare command in configuration for VSC Hortense

README.md
Another small hurdle before tagging v0.1.0...
=> clean up README file, refer to docs for installing/configuring/using EESSI test suite

eessi/testsuite/hooks.py
can be reused in the OSU benchmark
=> split off `assign_default_num_cpus_per_node` as separate hook

config/aws_citc.py, config/github_actions.py, config/izum_vega.py, config/settings_example.py, config/surf_snellius.py, config/vsc_hortense.py
This is done for all settings files. Please test in your own systems using gromacs test.
=> Adding mem to the resources part of all partitions.

config/it4i_karolina.py
Fix https://github.com/EESSI/software-layer/issues/456#issuecomment-2107755266 until we can more permanently fix it through an LMOD hook in host_injections
=> Fix for "Failed to modify UD QP to INIT on mlx5_0" on Karolina CI runs

eessi/testsuite/hooks.py
see also discussion in https://github.com/EESSI/test-suite/pull/139
=> set SRUN_CPUS_PER_TASK for srun launcher

.github/workflows/test.yml
=> use software.eessi.io repo in CI

README.md
Hopefully this helps to avoid mistakes like the one fixed in #147
=> add notes on release management to README

config/it4i_karolina.py, config/vsc_hortense.py
... one should simply specify this under the environment variable SBATCH_ACCOUNT
=> Remove SLURM account

eessi/testsuite/hooks.py
=> add hooks for measuring memory usage in a job

eessi/testsuite/common_config.py
reframe shows warnings in yellow, makes it easier to spot
=> use reframe warning

.github/workflows/scorecards.yml
Similar to https://github.com/EESSI/software-layer/pull/562
=> Update scorecards action

eessi/testsuite/tests/apps/lammps/lammps.py
this hook is now doing only 1 thing, so better to say exactly what it does
=> update lammps hook name

config/azure_mc.py
This issue show up at the very least in the quantumespresso test.
=> Fix MPI issue with workaround

RELEASE_NOTES, pyproject.toml
=> Release 0.5.1

eessi/testsuite/eessi_mixin.py
fixes https://github.com/EESSI/test-suite/issues/228
=> prefix mixin methods to avoid accidental overrides

config/settings_example.py
fixes https://github.com/EESSI/test-suite/issues/261
=> set SLURM_EXPORT_ENV=ALL in prepare_cmds of example config
